project:
  type: website

execute:
  freeze: auto

website:
  title: "Ormosia"
  favicon: images/chip_tree.svg
  google-analytics: "G-YNE42XN5HT"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - people.qmd
      - research.qmd
      - blogs.qmd
      - publications.qmd
      - resources.qmd
      - about.qmd
    right:
      - icon: google
        href: https://scholar.google.com/citations?user=jl95bUAAAAAJ&hl=en
        target: blank
      - icon: twitter
        href: https://twitter.com/wyujie666
        target: blank
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/silicormosia/silicormosia.github.io
            target: blank
          - text: Report an Issue
            url: https://github.com/silicormosia/silicormosia.github.io/issues
            target: blank

format:
  html:
    theme: sketchy
    css: styles.css
    toc: false
    grid:
      body-width: 1200px
      margin-width: 500px
