project:
  type: website

execute:
  freeze: auto

website:
  title: "Emerald"
  favicon: image/chip_tree.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - blogs.qmd
      - publications.qmd
      - about.qmd
    right:
      - icon: github
        href: https://github.com/silicormosia
      - icon: google
        href: https://scholar.google.com/citations?user=jl95bUAAAAAJ&hl=en
      - icon: twitter
        href: https://twitter.com/wyujie666
  google-analytics: "G-YNE42XN5HT"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
