---
title: "Publications"
---

# Journal Papers

## In Press

## 2023

- N. Holtzman, \colorbox{lightgray}{Y. Wang}, J. D. Wood, C. Frankenberg, and A. G. Konings (2023).
  Constraining plant hydraulics with microwave radiometry in a land surface model: Impacts of temporal resolution.
  Water Resources Research 59(11): e2023WR035481.
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/bibtex/holtzman2023constraining.bib">BIBTEX</a>
  <a href="https://doi.org/10.1029/2023WR035481">DOI</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/holtzman2023constraining.pdf">PDF</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/holtzman2023constraining-si.docx">SI</a>

- Y. Wang, and Y. Yin (2023).
  Agriculture in silico: Perspectives on radiative transfer optimization using vegetation modeling.
  Crop and Environment 2(4): 175-183.
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/bibtex/wang2023agriculture.bib">BIBTEX</a>
  <a href="https://doi.org/10.1016/j.crope.2023.07.003">DOI</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/wang2023agriculture.pdf">PDF</a>
  <a href="https://github.com/Yujie-WANG/Published-Codes-Yujie-WANG">CODE</a>

- R. K. Braghiere, Y. Wang, A. Gagné-Landmann, P. G. Brodrick, A. A. Bloom, A. J. Norton, S. Ma, P. Levine, M. Longo, K. Deck, P. Gentine, J. R. Worden, C. Frankenberg, and T. Schneider (2023).
  The importance of hyperspectral soil albedo information for improving Earth system model projections.
  AGU Advances 4(4): e2023AV000910.
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/bibtex/braghiere2023importance.bib">BIBTEX</a>
  <a href="https://doi.org/10.1029/2021AV000538">DOI</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/braghiere2023importance.pdf">PDF</a>
  <a href="https://github.com/Yujie-WANG/Published-Codes-Yujie-WANG">CODE</a>

- X. Liang, D. Wang, Q. Ye, J. Zhang, M. Liu, H. Liu, K. Yu, Y. Wang, E. Hou, B. Zhong, L. Xu, T. Lv, S. Peng, H. Lu, P. Sicard, A. Anav, and D. S. Ellsworth (2023).
  Stomatal responses of terrestrial plants to global change.
  Nature Communications 14(1): 2188.
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/bibtex/liang2023stomatal.bib">BIBTEX</a>
  <a href="https://doi.org/10.1038/s41467-023-37934-7">DOI</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/liang2023stomatal.pdf">PDF</a>

- Y. Wang, R. K. Braghiere, M. Longo, A. J. Norton, P. Köhler, R. Doughty, Y. Yin, A. A. Bloom, and C. Frankenberg (2023).
  Modeling global vegetation gross primary productivity, transpiration and hyperspectral canopy radiative transfer simultaneously using a next generation land surface model—CliMA Land.
  Journal of Advances in Modeling Earth Systems 15(3): e2021MS002964.
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/bibtex/wang2023modeling.bib">BIBTEX</a>
  <a href="http://dx.doi.org/10.1029/2021MS002964">DOI</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/wang2023modeling.pdf">PDF</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/wang2023modeling-si.pdf">SI</a>
  <a href="https://github.com/Yujie-WANG/Published-Codes-Yujie-WANG">CODE</a>

## 2022

- Y. Wang, and C. Frankenberg (2022).
  Technical note: Common ambiguities in plant hydraulics.
  Biogeosciences 19(19): 4705-4714.
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/bibtex/wang2022common.bib">BIBTEX</a>
  <a href="https://doi.org/10.5194/bg-19-4705-2022">DOI</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/wang2022common.pdf">PDF</a>
  <a href="https://github.com/Yujie-WANG/Published-Codes-Yujie-WANG">CODE</a>

- Y. Wang, P. Köhler, R. K. Braghiere, M. Longo, R. Doughty, A. A. Bloom, and C. Frankenberg (2022).
  GriddingMachine, a database and software for Earth system modeling at global and regional scales.
  Scientific Data 9: 258.
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/bibtex/wang2022griddingmachine.bib">BIBTEX</a>
  <a href="https://doi.org/10.1038/s41597-022-01346-x">DOI</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/wang2022griddingmachine.pdf">PDF</a>
  <a href="https://github.com/Yujie-WANG/Published-Codes-Yujie-WANG">CODE</a>

- R. Doughty, T. Kurosu, N. Parazoo, P. Köhler, Y. Wang, Y. Sun, and C. Frankenberg (2022).
  Global GOSAT, OCO-2 and OCO-3 solar induced chlorophyll fluorescence datasets.
  Earth System Science Data 14(4): 1513-1529.
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/bibtex/doughty2022global.bib">BIBTEX</a>
  <a href="https://doi.org/10.5194/essd-14-1513-2022">DOI</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/doughty2022global.pdf">PDF</a>

- Y. Wang, and C. Frankenberg (2022).
  On the impact of canopy model complexity on simulated carbon, water, and solar-induced chlorophyll fluorescence fluxes.
  Biogeosciences 19(1): 29-45.
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/bibtex/wang2022impact.bib">BIBTEX</a>
  <a href="https://doi.org/10.5194/bg-19-29-2022">DOI</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/wang2022impact.pdf">PDF</a>
  <a href="https://github.com/Yujie-WANG/Published-Codes-Yujie-WANG">CODE</a>

## 2021

- Y. Wang, P. Köhler, L. He, R. K. Braghiere, R. Doughty, J. Wood, and C. Frankenberg (2021).
  Testing stomatal models at the stand level in deciduous angiosperm and evergreen gymnosperm forests using CliMA Land (v0.1).
  Geoscientific Model Development 14(11): 6741-6763.
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/bibtex/wang2021testing.bib">BIBTEX</a>
  <a href="https://doi.org/10.5194/gmd-14-6741-2021">DOI</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/wang2021testing.pdf">PDF</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/wang2021testing-si.pdf">SI</a>
  <a href="https://github.com/Yujie-WANG/Published-Codes-Yujie-WANG">CODE</a>

- A. G. Konings, S. S. Saatchi, C. Frankenberg, M. Keller, V. Leshyk, W. R. L. Anderegg, V. Humphrey, A. M. Matheny, A. Trugman, L. Sack, E. Agee, M. L. Barnes, O. Binks, K. Cawse-Nicholson, B. O. Christoffersen, D. Entekhabi, P. Gentine, N. M. Holtzman, G. G. Katul, Y. Liu, M. Longo, J. Martinez-Vilalta, N. McDowell, P. Meir, M. Mencuccini, A. Mrad, K. A. Novick, R. S. Oliveira, P. Siqueira, S. C. Steele-Dunne, D. R. Thompson, Y. Wang, R. Wehr, J. D. Wood, X. Xu, and P. A. Zuidema (2021).
  Detecting forest response to droughts with global observations of vegetation water content.
  Global Change Biology 27(23): 6005-6024.
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/bibtex/konings2021detecting.bib">BIBTEX</a>
  <a href="https://doi.org/10.1111/gcb.15872">DOI</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/konings2021detecting.pdf">PDF</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/konings2021detecting-si.pdf">SI</a>

- P. Köhler, W. W. Fischer, G. R. Rossman, J. P. Grotzinger, R. Doughty, Y. Wang, Y. Yin, and C. Frankenberg (2021).
  Mineral luminescence observed from space.
  Geophysical Research Letters 48(19): e2021GL095227.
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/bibtex/kohler2021mineral.bib">BIBTEX</a>
  <a href="https://doi.org/10.1029/2021GL095227">DOI</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/kohler2021mineral.pdf">PDF</a>

- R. K. Braghiere, Y. Wang, R. Doughty, D. Souza, T. Magney, J. Widlowski, M. Longo, A. Bloom, J. Worden, P. Gentine, and C. Frankenberg (2021).
  Accounting for canopy structure improves hyperspectral radiative transfer and sun-induced chlorophyll fluorescence representations in a new generation Earth System model.
  Remote Sensing of Environment 261: 112497.
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/bibtex/braghiere2021accounting.bib">BIBTEX</a>
  <a href="https://doi.org/10.1016/j.rse.2021.112497">DOI</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/braghiere2021accounting.pdf">PDF</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/braghiere2021accounting-si.pdf">SI</a>
  <a href="https://github.com/Yujie-WANG/Published-Codes-Yujie-WANG">CODE</a>

- A. Potkay, A. T. Trugman, Y. Wang, M. D. Venturas, W. R. L. Anderegg, C. Mattos, and Y. Fan (2021).
  Coupled whole-tree optimality and xylem-hydraulics explain dynamic biomass partitioning.
  New Phytologist 230(6): 2226-2245.
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/bibtex/potkay2021coupled.bib">BIBTEX</a>
  <a href="https://doi.org/10.1111/nph.17242">DOI</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/potkay2021coupled.pdf">PDF</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/potkay2021coupled-si.pdf">SI</a>

- Y. Wang, W. R. L. Anderegg, M. D. Venturas, A. T. Trugman, K. Yu, and C. Frankenberg (2021).
  Optimization theory explains nighttime stomatal responses.
  New Phytologist 230(4): 1550-1561.
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/bibtex/wang2021optimization.bib">BIBTEX</a>
  <a href="https://doi.org/10.1111/nph.17267">DOI</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/wang2021optimization.pdf">PDF</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/wang2021optimization-si.pdf">SI</a>
  <a href="https://github.com/Yujie-WANG/Published-Codes-Yujie-WANG">CODE</a>

## 2020

- Y. Wang, J. S. Sperry, W. R. L. Anderegg, M. D. Venturas, and A. T. Trugman (2020).
  Tansley Review: A theoretical and empirical assessment of stomatal optimization modeling.
  New Phytologist 227(2): 311–325.
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/bibtex/wang2020theoretical.bib">BIBTEX</a>
  <a href="https://doi.org/10.1111/nph.16572">DOI</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/wang2020theoretical.pdf">PDF</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/wang2020theoretical-si.pdf">SI</a>
  <a href="https://github.com/Yujie-WANG/Published-Codes-Yujie-WANG">CODE</a>

## 2019

- J. S. Sperry, M. D. Venturas, H. N. Todd, A. T. Trugman, W. R. L. Anderegg, Y. Wang, and X. Tai (2019).
  The impact of rising CO₂ and acclimation on theresponse of US forests to global warming.
  Proceedings of the National Academy of Sciences of the United States of America 116(51): 25734–25744.
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/bibtex/sperry2019impact.bib">BIBTEX</a>
  <a href="https://doi.org/10.1073/pnas.1913072116">DOI</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/sperry2019impact.pdf">PDF</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/sperry2019impact-si.zip">SI</a>

- A. T. Trugman, L. D. L. Anderegg, J. S. Sperry, Y. Wang, M. D. Venturas, and W. R. L. Anderegg (2019).
  Leveraging plant hydraulics to yield predictive and dynamic plant leaf allocation in vegetation models with climate change.
  Global Change Biology 25: 4008–4021.
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/bibtex/trugman2019leveraging.bib">BIBTEX</a>
  <a href="https://doi.org/10.1111/gcb.14814">DOI</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/trugman2019leveraging.pdf">PDF</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/trugman2019leveraging-si.pdf">SI</a>

- Y. Wang, J. S. Sperry, M. D. Venturas, A. T. Trugman, D. D. Love, and W. R. L. Anderegg (2019).
  The stomatal response to rising CO₂ concentration and drought is predicted by a hydraulic trait-based optimization model.
  Tree Physiology 39(8): 1416–1427.
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/bibtex/wang2019stomatal.bib">BIBTEX</a>
  <a href="https://doi.org/10.1093/treephys/tpz038">DOI</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/wang2019stomatal.pdf">PDF</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/wang2019stomatal-si.pdf">SI</a>
  <a href="https://github.com/Yujie-WANG/Published-Codes-Yujie-WANG">CODE</a>

- K. Yu, G. R. Goldsmith, Y. Wang, and W. R. L. Anderegg (2019).
  Phylogenetic and biogeographic controls of plant nighttime stomatal conductance.
  New Phytologist 222(4): 1778–1788.
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/bibtex/yu2019phylogenetic.bib">BIBTEX</a>
  <a href="https://doi.org/10.1111/nph.15755">DOI</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/yu2019phylogenetic.pdf">PDF</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/yu2019phylogenetic-si.pdf">SI</a>

- G. Du, F. Feng, Y. Wang, and M. T. Tyree (2019).
  Do nano-particles cause recalcitrant vulnerability curves in Robinia? Testing with a four-cuvette Cochard rotor and with water extraction curves.
  Tree Physiology 39(1): 156–165.
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/bibtex/du2019nano.bib">BIBTEX</a>
  <a href="https://doi.org/10.1093/treephys/tpy051">DOI</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/du2019do.pdf">PDF</a>


## 2018

- D. M. Love, M. D. Venturas, J. S. Sperry, P. D. Brooks, J. L. Pettit, Y. Wang, and W. R. L. Anderegg (2018).
  Dependence of aspen stands on a subsurface water subsidy: Implications for climate change impacts.
  Water Resource Research 55(3): 1833–1848.
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/bibtex/love2019dependence.bib">BIBTEX</a>
  <a href="https://doi.org/10.1029/2018WR023468">DOI</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/love2019dependence.pdf">PDF</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/love2019dependence-si.zip">SI</a>

- M. D. Venturas, J. S. Sperry, D. M. Love, E. H. Frehner, M. G. Allred, Y. Wang, and W. R. L. Anderegg (2018).
  A stomatal control model based on optimization of carbon gain versus hydraulic risk predicts aspen sapling responses to drought.
  New Phytologist. 220(3): 836–850.
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/bibtex/venturas2018stomatal.bib">BIBTEX</a>
  <a href="https://doi.org/10.1111/nph.15333">DOI</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/venturas2018stomatal.pdf">PDF</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/venturas2018stomatal-si.zip">SI</a>
  <a href="https://github.com/Yujie-WANG/Published-Codes-Yujie-WANG">CODE</a>

## 2017

- J. S. Sperry, M. D. Venturas, W. R. L. Anderegg, M. Mencuccini, D. S. Mackay, Y. Wang, and D. M. Love (2017).
  Predicting stomatal responses to the environment from the optimization of photosynthetic gain and hydraulic cost.
  Plant Cell & Environment 40(6): 816–830.
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/bibtex/sperry2017predicting.bib">BIBTEX</a>
  <a href="https://dx.doi.org/10.1111/pce.12852">DOI</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/sperry2017predicting.pdf">PDF</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/sperry2017predicting-si.pdf">SI</a>
  <a href="https://github.com/Yujie-WANG/Published-Codes-Yujie-WANG">CODE</a>

## 2016

- J. S. Sperry, Y. Wang, B. T. Wolfe, D. S. Mackay, W. R. L. Anderegg, N. G. McDowell, and W. T. Pockman (2016).
  Pragmatic hydraulic theory predicts stomatal responses to climatic water deficits.
  New Phytologist. 212(3): 577–589.
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/bibtex/sperry2016pragmatic.bib">BIBTEX</a>
  <a href="https://dx.doi.org/10.1111/nph.14059">DOI</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/sperry2016pragmatic.pdf">PDF</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/sperry2016pragmatic-si.pdf">SI</a>
  <a href="https://github.com/Yujie-WANG/Published-Codes-Yujie-WANG">CODE</a>

## 2015

- Y. Wang, J. Liu, and M. T. Tyree (2015).
  Stem hydraulic conductivity depends on the pressure at which it is measured and how this dependence can be used to assess the tempo of bubble pressurization in recently cavitated vessels.
  Plant Physiology 169(4): 2597–2607.
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/bibtex/wang2015stem.bib">BIBTEX</a>
  <a href="https://doi.org/10.1104/pp.15.00875">DOI</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/wang2015stem.pdf">PDF</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/wang2015stem-si.pdf">SI</a>
  <a href="https://github.com/Yujie-WANG/Published-Codes-Yujie-WANG">CODE</a>

- Y. Wang, R. Pan, and M. T. Tyree (2015).
  Studies on the tempo of bubble formation in recently cavitated vessels: A model to predict the pressure of air bubbles.
  Plant Physiology 168(2): 521–531.
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/bibtex/wang2015studies.bib">BIBTEX</a>
  <a href="https://doi.org/10.1104/pp.114.256602">DOI</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/wang2015studies.pdf">PDF</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/wang2015studies-si.pdf">SI</a>
  <a href="https://github.com/Yujie-WANG/Published-Codes-Yujie-WANG">CODE</a>

## 2014

- Y. Wang, R. Burlett, F. Feng, and M. T. Tyree (2014).
  Improved precision of hydraulic conductance measurements using a Cochard rotor in two different centrifuges.
  Journal of Plant Hydraulics 1: e-0007.
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/bibtex/wang2014improved.bib">BIBTEX</a>
  <a href="http://dx.doi.org/10.20870/jph.2014.e007">DOI</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/wang2014improved.pdf">PDF</a>
  <a href="https://github.com/Yujie-WANG/Published-Codes-Yujie-WANG">CODE</a>

## Earlier

- J. Liu, P. Fu, Y. Wang, and K. Cao (2012).
  Different drought-adaptation strategies as characterized by hydraulic and water-relations traits of evergreen and deciduous figs in a tropical karst forest.
  Plant Science Journal 30(5): 484-493.
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/bibtex/liu2012different.bib">BIBTEX</a>
  <a href="https://en.cnki.com.cn/Article_en/CJFDTOTAL-WZXY201205006.htm">DOI</a>
  <a href="https://github.com/silicormosia/silicormosia.github.io/raw/main/papers/liu2012different.pdf">PDF</a>
