---
title: "Visiting Mel (1)"
image: ../../images/
description: "上一次见Mel还是2017年，不想已经时隔7年。。。"
author: "Yujie Wang"
date: "12/14/2024"
categories:
  - 随笔
---

终于在几周前确定了回国的行程，Mel彼时正好在中国，我回国也赶不上见他老人家，于是便打电话给Charleen讲了我要回国的事情。我本想回国时间过于仓促，只是嘘寒问暖一下，以后有空去看望Mel和她，却得知她在不久前不幸因中风导致右眼失明。我一时间语塞，不知该说什么，非常后悔这段时间没有去看望过她和Mel，毕竟在今年5月份参加Gordon会议后可以过来一趟的。Mel和Charleen夫妇对我非常照顾，虽然年龄上他们只比我爷爷奶奶小上几岁，对我来说他们更像父母。原因大概在于师徒关系，以及机缘巧合下我带过Charleen和她儿子儿媳在中国旅游。想起来我用蹩脚的英语给她们解释文化、历史、风俗等等，这些往事依然历历在目。

最初认识Mel时是2012年秋天，当时我还是研二刚从科大上完课回植物园，正在西双版纳热带植物园做实验，曹坤芳老师忽然跟我们讲有个Three教授回来访问。我当时正好在做一些植物水力学的实验，发现了一些奇怪但可重复的结果，正踌躇满志想要发一篇New Phytologist（领域的神圣期刊）。我当时好奇Three教授是谁啊，没听说过啊，自然也没有放在心上。一开始是同年级的张亚同学去接待Mel的访问，后来见面才知道是Tyree教授，植物水力学方向的大佬，这才有了跟Mel的第一次见面。Mel对我的实验结果并不感兴趣，我也没能说服他。大佬嘛，都有自己的脾气不是，毕竟作为非大佬的我都眼高于顶。随后，我在自己的新发现越来越远，努力做实验总结新发现，也试图写文章。现在回想起来都恨不得找个地缝钻进去，根本没有经过系统训练的我为啥会那么自信呢。我不知道当时我是否有记录过自己的心情，如果有，一定会找出来烧掉。

第二次见Mel是在一个比较迷茫的时间，现在回想起来都感慨万千。就在Mel访问后不久，我们得知了曹老师因为年龄与健康的原因决定去广西大学，因此一时间我不知何去何从。作为刚入学的学生，我们可以跟着去广西大学去做实验，也可以继续留在组里，毕竟曹老师还有些遗留的经费。由于广西大学比中科院研究所要差的远，跟中国科学技术大学更没得比（我是联合培养的学生），我自然不会去广西大学，也就只得坐吃山空了，而最大的问题就在于缺乏指导，而我却对此没有多大危机感。我当时有一系列想做的研究，曹老师也都挺支持，也同意我自主地做自己喜欢的研究，也乐于不用指导。可能是因为我算是中科大的“高材生”，曹老师对我的支持（与容忍）要比对其他学生高，我后来好像也听说过别人对此颇有微词，当然这些也不重要了。

得知曹老师确定要去广西之后，我觉得在版纳也是做实验，在家也是做实验，我干脆带些设备回家做实验得了，曹老师竟然同意了，我也在2013年初带着金玉回了老家在那做了些实验（当时我们还没有结婚，想想金玉对我的支持付出也是巨大的）。现在想想我的确是有些新发现的，但种种原因之下并没有发表任何文章（主要是我写作不好，后来也没继续做新的实验）。在家期间我写好了文章发给曹老师，他则咨询了Mel，Mel表示完全不相信我的结果。于是为了说服他，我就决定去杨凌（西北农林所在地）去展示给Mel我的结果是可以重复的。金玉家正好是咸阳的（杨凌在咸阳市武功县），她也乐意回了家，后来便在咸阳及西安工作了。2013年春夏之交到了杨凌，Mel非常好客，让我住在了他的公寓，或许正因为此才跟他结下了更深的师徒情分。
