---
title: "Visiting Mel (4)"
image: ../../images/
description: "上一次见Mel还是2017年，不想已经时隔7年。。。"
author: "Yujie Wang"
date: "12/14/2024"
categories:
  - 随笔
---

工作方面，因为Mel从加拿大运来中国的两台离心机很贵、无法维护、而且制冷效果不好，这影响Mel开展栓塞疲劳和长导管植物测定方法的研究，所以Mel后来试图寻求中国离心机厂商定制离心机和转子。最终也找到了一家愿意合作的厂商——湘仪，并开始花钱给他们实验转子的研发。与此同时，Mel在去了法国看了他们超级大转子以及相机界面之后，也希望能添加高速摄影机以提高安全性，于是他也买了工业相机并联系了北校区一个老师想找他帮忙编写软件。然而在湘仪给我们运过来第一台离心机之后，北区的计算机老师那边迟迟没有进展，我们最后也只得自己来。早在这之前，我觉得Mel的软件测量的数据误差有些大，而这种误差可以通过拟合曲线的方式解决，于是我便自学Python编写了一个新的软件，并且在自己做实验的时候开始使用自己的软件。这点或许让Mel感到特别意外，后来我也在他的帮助下进一步完善了拟合方法（我之前用的是近似解）。我想着反正我要用自己的软件，不如就顺便添加新的离心机支持，因此便花了不少时间去编写新的软件，这也顺利地成功运行了新的离心机，推动了它的商业化。由于我们这边有了新离心机，Mel也就转手把两台旧的离心机送人了，一台送给了林学院的蔡靖老师，一台送给了水保所的李秧秧老师。

我在建模与编程上的能力，外加对植物水分运输系统的理解让Mel对我刮目相看，他也极力向他的博后John Sperry推荐我，称我是他最得意的学生之一（John自然也是其中之一）。当然，这样的称赞自然让我高兴了好久，同样也让我变得有些骄傲因而没有意识到自己的缺点——不够谦逊。后来，经历了社会多年的毒打，最终也勉强算是改变了吧。这里也要感谢John有意或者无意的帮助，过几天去看望他时得跟John确认一下。之后就是日复一日地做实验、改文章的日常，直到我接到了犹他大学的录取通知，之后就是准备要出国了。说到出国，因为晨哥在2014就出国去欧洲留学了，因此在2014到2015年Mel换了新的秘书，但是并没有像晨哥那般跟Mel插科打诨。Mel在这段时间也比较忙，他也和清华大学的老师学生们合作，清华那边的学院也打算把Mel挖去，但最后不了了之了，应该是西北农历不放手吧。

整体来说，Mel在西北农林的科研生涯挺顺利，培养了一些新的博士后、学生等等，然后他和行政方面的关系貌似并不好，或许是因为他中间打算跳槽的缘故，或许就是因为行政方面的原因他才打算跳槽，这我就不知道也不能下揣测。在我出国的时候，Mel就在打算招人来接替他的位置了，兜兜转转并没有找到合适的且愿意去的，实验室人员也或多或少有些纠纷，这也都是我的道听途说。其实我也想接替Mel的位置，只是当时我作为一个硕士后并没有“夺嫡”的资格（哈哈）。因此，我老老实实地去美国留学了。

我刚去犹他的时候，Charleen还专门飞去盐湖城并租了辆车帮我们安顿，她帮我们不少忙：代交了房租领了钥匙、带我们去亚洲超市等等。Mel和Charleen在第二年暑假刚开始的时候给我买了机票邀请我和金玉去他家玩。期间，我们在Vermont和New York州各待了几天，坐了Champlain的轮渡、参观了Ben-Jerry工厂、参观了巧克力工厂等，Mel还专门带我们开车去哈佛大学去认识他另外一个得意弟子Missy Holbrook。也是在那期间，我们发现金玉怀孕了，我们也想给孩子起名Melvin或者Charleen，但不确定是不是不礼貌。Mel最后也给我和金玉第一个孩子起名Melanie，昵称也是Mel。Mel透露说他起这么名字的原因是他小时候上学时班里女同学喊Mel时他误以为是喊自己，后来才知道有个叫Melanie的同学。既然Melanie的昵称也是Mel，这也是变相的name after him了。因为Tyson和Alison觉得Melanie这个名字很好听，所以他们也给自己家的二女儿命名Malaney。再后来，我和金玉的第二个孩子则是拜托John起的名字，因而我家老二Jonathan便是name after John了，此是后话不提。

Mel在千人计划结束之后并没有和西北农林续约，而是在浙师大的杨冬梅老师的帮助下去浙师大任职了，我出国后跟Mel的联系也越来越少，只是偶尔才有邮件联系。我们也没有在国际会议里遇到过，其实他应该可以去参加Gordon Research Conference的。我在犹他的时候也试图跟Mel继续合作写文章，但Mel并没有再帮我修改过文章，或许是因为他觉得我应该独立、或许他觉得我应该找John、或许他觉得我要发表的东西不严谨、或许他只是太忙了。由于我并没有跟Mel系统地学习过写作，我经常被批判写作太差，后来我也放弃了。现在再想起来，差的原因或许在于那些成果并不值得发表，也许经年之后我会再把旧事拾起再重新改进。只是可惜自出国之后，我再也没有和Mel合作了。
