---
title: "Visiting Mel (6)"
image: ../../images/
description: "上一次见Mel还是2017年，不想已经时隔7年。。。"
author: "Yujie Wang"
date: "12/14/2024"
categories:
  - 随笔
---

我偷偷端详了Charleen，并没有看出她研究有任何异常，而且她还能开车，但她需要Mel提醒她车距以防出现车祸。这或许是她开特斯拉的原因，因为特斯拉又辅助驾驶防止出现车祸。Mel和Charleen说话的方式依旧是相敬如宾风格，并没有什么插科打诨，这也是属于他们的浪漫吧。我们很快就到了他们的公寓，不禁让我想起以前在他们公寓里的温馨时刻，只是这次金玉要在家带孩子不方便过来。依旧是熟悉的沙发、熟悉的厨房、熟悉的客厅、熟悉的布局，唯一变的就是我们的年龄。简单的嘘寒问暖后，我便再问到Mel和Charleen的健康，Charleen也将这些事儿娓娓道来。

Charleen在Burlington依旧定期参加纺织小组，然而在一次纺织聚会上她忽然就觉得右眼一黑。Charleen最初以为是眼角膜脱落，于是便找了一家诊所去看，然而并没有查出任何异常。等辗转到了急诊室，并看到医生其实已经是几个小时之后了，等做完一系列的检查更是不知过了多久。然而并没有查出是什么原因导致的右眼失明，在分析了MRI的结果之后，只能猜测是中风导致的眼部神经缺少供氧。后来在Charleen回到家之后慢慢查询，也了解到一般来说在神经缺少供氧之后三小时神经就会坏死，她也回忆道等她从诊所到了急诊室的时候应该也已经超过了三个小时，看来她也有些后悔当时没有直接去急诊室。我只听说单只眼无法判断距离，但捂着一只眼明显和一只眼失明不一样。在Charleen停车的时候我就发现她不能很好地把车停到线内，即使她倒回去一点再矫正，和旁边的车想必也是歪着的。我也能看出她在走路时，展示出比以往没有的保护姿态，即双手稍微上扬，以防撞到什么或者跌倒。Mel自然比较乐观，还玩笑道，至少比中风之后瘫痪要强得多。这确实是真的，我听过最多的也是中风瘫痪，但Charleen没有被逗笑，看来她还没有完全走出来。Charleen走路也比较慢，其中还有个原因是她心脏有些毛病，导致血液供氧不好，而手术风险也很大。这使得Charleen只能做缓慢的运动，哪怕慢跑都不行。

Mel也有自己的健康问题，他跟我解释道是癫痫，表现的症状就是有可能忽然失去对身体的控制，虽然大脑依旧活跃也能听到别人说话但是身体却不能行动。他经过查阅书籍与网络，也对癫痫有了更多的认识，比如说在五岁以前的孩子身上会偶尔出现，而这些小朋友在长大之后也会恢复；癫痫同样会在老人身上出现，但概率要更低；癫痫出现的原因或许在于大脑过于活跃等等。因此，为了防止其再次发生，Mel要每日服用药物来降低大脑活跃程度，而副作用可能会引起内脏的损伤，因此要定期作检查看是否有内脏损伤。Mel第一次使用的药物在半年后背发现对他肝脏有损伤，因此换过一种药。因为这种药属于处方药，并不能一次性大量获取，而这种药在中国也没有，因此Mel不得不考虑终止在浙江师范大学的合同。除此之外，因为药物是通过降低大脑活动的方式来防止癫痫的发作，其不免会影响人的短时记忆，而这对科研人员来说是无解的，比如在写作的时候会忘记写作的逻辑等等。除此之外，这对Mel的长期思考也有很大影响，比如今天想到了一个主意，但第二天可能会忘记等等，而本人对此更是无法察觉。Mel风趣地自嘲道他看了很多医学相关的书籍，都快成了一个真的doctor了，如果自己不忘记这些知识的话。我也开玩笑问他过两天会不会忘记我曾经来过，然后就是两个人的大笑。

Mel和浙江师范大学在第一个三年合约结束的时候就因为税务的问题决定不再继续，但浙师大还是保留了Mel的职位。由于Mel的名气很大，并且目前依旧有很多的引用，他的贡献对学院申请博士点至关重要。所以学院那边给了Mel优渥的合同，只要求Mel继续在学院挂职。然后由于中美关系紧张、在中国的工资需要在中美同时纳税、Mel的健康并不允许他有效地工作等原因，Mel决定将他的“工资”全投入到一个基金中去。这个基金将以经费奖励的方式，发给申请到其他研究经费的课题组，用来进一步推动学院的发展。因此，最终Mel以挂名誉职的方式为学院成立一个学术基金，也不旺为一桩美谈。浙师大方面自然也希望Mel每年能花些时间去一趟，但长时间的国际航班其实并不美好。我自然也希望Mel能偶尔去中国，这样我也可以带他看看我的单位、在安徽欣赏欣赏美景等。然而，或许这些以后并不会发生，反而该是我应该经常去看望看望他老人家。
