---
title: "Visiting Mel (5)"
image: ../../images/
description: "上一次见Mel还是2017年，不想已经时隔7年。。。"
author: "Yujie Wang"
date: "12/14/2024"
categories:
  - 随笔
---

在2024年5/6月份时，应该是Gordon Conference后，我跟Mel讲有可能需要他写推荐信的时候，我们聊到他的健康问题。Mel告诉我他发作过癫痫，身体根本动不了。他也跟我讲了他因为吃药身体瘦了很多，但也因此体重上反而更健康。由于用药不方便的原因，Mel决定中止和浙师大的合同，因为他不能继续做科研了。一方面，我为他不能继续做他喜欢的事业、而植物水力学也再次退休一位大佬而感到惋惜；另一方面，我也觉得他的健康更重要、他也需要和Charleen安享退休后的生活。Charleen由于想住的离孙女们更近，不想在New York和Vermont之间交通花太长时间，于是他们就把原来的房子和地卖掉了，换了一个离Vermont更近的地方（依然在纽约），为此就要重新做太阳能等等，Mel的确也非常喜欢这种工程。听说他们这样的退休生活，我也着实为他们感到开心。

然而就在几个月后，在我兴致勃勃打电话告诉Charleen和Mel我打算回国的事情，准备电话跟他们告别的时候，却听说Charleen因为中风而一只眼失明的消息。一时间我想到了我在23年底因准备去香港面试回家时奶奶身体还可以，仅过去了几个月她老人家就离开了。我立刻就决定要去看望他们一下，说得难听一点，万一某天他们谁忽然离世，我得后悔成什么样。恰好赶上要去华盛顿特区参加AGU的年会，我就打算在期间飞去Vermont一趟。好在我的海报与报告都在周二，我也就空出了周三和周四出来，于是便决定飞一趟去看望他们。

虽然周二忙了一天，为了去看Mel和Charleen，我周三大清早5点就起床，梳洗过后就匆匆下楼了。偏赶上了天气不好，已经在淅淅沥沥下雨了。好在去地铁站一路也算是直路，也没有在路上遇到流浪汉（或许是因为下雨的原因吧）。华盛顿特区的地铁还算是很方便的，虽然我第一次并不知道怎么操作，是工作人员帮我办的卡，告诉我充多少钱。事后我发现还是比较容易的，如果有个图片版的图就更好了，当然手机软件也可以用，不过没有支付宝的乘地铁功能方便（外国人不一定认为支付宝方便）。凌晨的地铁站并没有多少人，地铁也很方便就到了IAD机场并过了安检。

去Burlington的飞机是UA家的小飞机，可能因为太早的原因并没有多少人，感觉有一半位置是空的。飞机很快就到了BTV机场，BTV机场很小，一下飞机就被指引到一个小楼梯，下了楼梯就到了行李处。这时，我一眼就找到了在大厅徘徊的Mel，认出了他的背影。Mel留着一个短的马尾，我方才想起来之前在视频电话以及照片里见过他留长发的样子，但亲自看到他时，感觉还是不一样的。和上次见面比起来，Mel又苍老了不少，也明显没有了当年初见他时那精神矍铄的样子。他的头发也变得更稀疏，由于发型的原因，他从学者风格变成了艺术家风格。Burlington也下着小雨，出了机场后立刻就感觉到了冷风嗖嗖，也能看到路边没有融化的积雪。Mel告诉我雪下的有些早，但并没有停留，一般要到了圣诞节才会有大的降雪。我们等了一小会儿，Charleen就开着他们的特斯到了我们面前，依旧是当年那个WIND PWRD的车牌。Charleen变化相对小一些，或许只是因为发型没有变化的原因。
